#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0 
bspc config window_gap         20 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

killall -q polybar
while pgrep -u 1000 -x polybar >/dev/null; do
  sleep 0.02;
done
killall -q dunst
while pgrep -u 1000 -x dunst >/dev/null; do
  sleep 0.02;
done
dunst &
#####################
##      SXHKD      ##
#####################
killall -q sxhkd
while pgrep -u 1000 -x sxhkd >/dev/null; do
  sleep 0.02;
done
sxhkd &;
if [[ $(cat /sys/class/drm/card0-HDMI-A-1/status) == "connected" || $(cat /sys/class/drm/card0-HDMI-A-2/status) == "connected" ]] {
  echo "HDMI-2 connected";
  xrandr --output HDMI-2 --mode 1920x1200 --primary --right-of eDP-1;
  polybar top-ext &;
  polybar bottom-ext &;
  bspc monitor HDMI-2  -d 7 8 9 10
  bspc monitor eDP-1 -d 1 2 3 4 5 6
} else {
  echo "HDMI-2 not connected";
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
}
#####################
##      BSPWM      ##
#####################
bspc config border_width   2
bspc config window_gap     0
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#'#0A0A2B'
#'#B77DD7'
#'#A26FBF'
."/home/tarekali/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2" 
bspc config focused_border_color "$color15"

bspc config presel_feedback_color "$color1"

#####################
##     Polybar     ##
#####################
polybar top &;
polybar bottom &;


